### ISSUE TITLE
Chrome failed to start & DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by GGaitanis** [roschaefer/rundfunk-mitbestimmen#866]
Hi experts,

I am trying to install and initiate the app but I am exepriencing below issues:

[ec2-user@ip-172-31-39-145 InstaPy]$ python quickstart.py
ERROR [2018-10-13 17:37:00] [INSTA_NAME]  Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.14.62-65.117.amzn1.x86_64 x86_64)
Traceback (most recent call last):
  File "/home/ec2-user/InstaPy/instapy/instapy.py", line 340, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.14.62-65.117.amzn1.x86_64 x86_64)

Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    headless_browser=False)
  File "/home/ec2-user/InstaPy/instapy/instapy.py", line 224, in __init__
    self.set_selenium_local_session()
  File "/home/ec2-user/InstaPy/instapy/instapy.py", line 344, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/ec2-user/InstaPy/assets/chromedriver

Can you please provide your assistance?

Thank you,
George

**Comment by GGaitanis** [comment]
One more detail about versions:
[ec2-user@ip-172-31-39-145 InstaPy]$ google-chrome --version
Google Chrome 69.0.3497.100
[ec2-user@ip-172-31-39-145 InstaPy]$ chromedriver --version
ChromeDriver 2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac)

**Comment by roschaefer** [comment]
HI @GGaitanis is it possible that you opened the issue in a wrong repository? We use Ruby+JavaScript but no Python. What is InstaPy? Maybe this [software here](https://github.com/timgrossmann/InstaPy)?

**Comment by roschaefer** [comment]
closing, probably unrelated
