### ISSUE TITLE
Error while running the ember test --server command.

### ISSUE THREAD

**Issue by faithngetich** [roschaefer/rundfunk-mitbestimmen#884]
## Expected Behavior

Running ```cd frontend && ember test --server``` should run correctly
## Current Behavior

Running this command returns the error shown in the screenshot below.
## Possible Solution

N/A
## Steps to Reproduce

Run ```cd frontend && ember test --server``` on your terminal. 

## Environment
 - Operating System: Mac OS version 10.13.6
 - Browser & Version:
 - Device (Android/iPhone/PC):

## Additional context

<img width="1440" alt="screen shot 2018-10-23 at 00 18 05" src="https://user-images.githubusercontent.com/23743836/47320360-e491e480-d659-11e8-8e01-6654a8affba8.png">

**Comment by roschaefer** [comment]
Uh, this seems to be a nasty bug.

Does this happen in docker or without docker?

You could try to `rm -rf node_modules && yarn install` and see if the problem persists.

**Comment by mattwr18** [comment]
I have tried those commands above and now I am getting this output in the frontend server
```
WARNING: Async Request leaks detected. Add a breakpoint here and set `store.generateStackTracesForTrackedRequests = true;`to inspect traces for leak origins:
	 - DS: Handle Adapter#queryRecord of summarized-statistic
[object Object]
    at logWarning (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/@ember/debug/lib/warn.js:47:1)
    at HANDLERS.(anonymous function) (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/@ember/debug/lib/handlers.js:11:1)
    at invoke (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/@ember/debug/lib/handlers.js:20:1)
    at Object.warn (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/@ember/debug/lib/warn.js:93:1)
    at Class.willDestroy (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/addon-tree-output/ember-data/-private.js:12682:1)
    at Class.superWrapper [as willDestroy] (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/ember-utils.js:308:1)
    at invokeWithOnError (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/backburner.js:256:1)
    at Queue.flush (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/backburner.js:167:1)
    at DeferredActionQueues.flush (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/backburner.js:326:1)
    at Backburner._end (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/backburner.js:748:1)
    at Backburner._boundAutorunEnd (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/backburner.js:483:1)
    at run (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/vendor/babel-polyfill/polyfill.js:4237:1)
    at /tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/vendor/babel-polyfill/polyfill.js:4254:1
    at flush (/tmp/broccoli-29700j8DD6431bMQL/out-519-broccoli_persistent_filter_replace_filter/assets/vendor/babel-polyfill/polyfill.js:1422:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I am able to visit the site, no problem; however, when I try to run this test `bundle exec cucumber features/find-broadcasts/new/validate_broadcast.feature`, I am getting this in the test  output:
```
Given I am logged in # features/step_definitions/steps.rb:15
      Unable to find link or button "Log in" (Capybara::ElementNotFound)
      ./features/step_definitions/steps.rb:12:in `login'
      ./features/step_definitions/steps.rb:18:in `/^I am logged in$/'
      features/find-broadcasts/new/validate_broadcast.feature:18:in `Given I am logged in'
```
and this in the server output:
https://gist.github.com/mattwr18/98aabe78f766e1fc5b4781301b6a3d8e#file-nasty-frontend-error
