### ISSUE TITLE
redis needed for running rails db:seed

### ISSUE THREAD

**Issue by dkuku** [roschaefer/rundfunk-mitbestimmen#931]
I could not seed the local database with rails db:seed without starting redis. 
There's nothing in the docs about redis

## Current Behavior
```
# rails db:seed                                                                                                                                                
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
/home/kuku/Projects/rundfunk-mitbestimmen/backend/app/models/impression.rb:19:in `block in <class:Impression>'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:86:in `block (2 levels) in <top (required)>'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:79:in `each'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:79:in `block in <top (required)>'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:78:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:6379
/home/kuku/Projects/rundfunk-mitbestimmen/backend/app/models/impression.rb:19:in `block in <class:Impression>'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:86:in `block (2 levels) in <top (required)>'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:79:in `each'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:79:in `block in <top (required)>'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:78:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
IO::EINPROGRESSWaitWritable: Operation now in progress - connect(2) would block
/home/kuku/Projects/rundfunk-mitbestimmen/backend/app/models/impression.rb:19:in `block in <class:Impression>'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:86:in `block (2 levels) in <top (required)>'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:79:in `each'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:79:in `block in <top (required)>'
/home/kuku/Projects/rundfunk-mitbestimmen/backend/db/seeds.rb:78:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

## Expected Behavior
```
# sudo systemctl start redis                                                                                                                              

# rails db:setup                                                                                                                                               
Created database 'rundfunk-backend-development'
Created database 'rundfunk-backend-test'
 set_config
------------

(1 row)

 set_config
------------

(1 row)

2018-11-14T21:29:26.528Z 31934 TID-gt0f7iqde INFO: Adding dead ComputeSimilaritiesWorker job 1e385d2eb95a1d53b9e71f83
2018-11-14T21:29:26.567Z 31934 TID-gt0f7iqde INFO: Adding dead ComputeSimilaritiesWorker job e5563d41f95dc4a35a039596

```
## Possible Solution
We should add a info to the documentation about redis

## Environment
 - Linux

**Comment by roschaefer** [comment]
@dkuku great find! You are doing the setup without docker? Please add instructions to the README.md that we need a running Postgres **and** a redis database.

**Comment by dkuku** [comment]
Yeah, without docker. Everything went smoothly. The page is running locally. I could run the rspec tests. Last thing I have to fix is running the cukes, because I have a problem with the communication with chrome
